# -*- coding: utf-8 -*-
"""L3_TD1_LUCAS_SIMATOVIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ez_HKHOfDKFvR5k9X2Il-i8sz58VxTK5
"""

import numpy as np

#on génère une matrice de 5000 échantillons

z = np.zeros((5000 , 1))
print("générer une matrice qu'avec des zéros :")
print(z)

p = np.array([[0.6 , 0.4]])
F = np.cumsum(p)
print("probabilité des deux lois gaussiennes: ",p)
print("fonction de répartition F(x) = somme des probabilités de tirage des deux lois gaussiennes: ",F)

#on établit les deux lois gaussiennnes

m = np.array([[-2.3] , [3.3]])
sigma = np.array([[2] , [3.1]])

for i in range (5000):
    Ui = np.random.rand(1,1)
    j = 0
    while(Ui > F[j]):
        j = j+1

    #on calcul la probabilité de réalisation des 5000 lancés un à un

    print("INDIQUE SI LA PIÈCE TOMBE SUR PILE OU FACE ACCOMPAGNE DE LA PROBABILITÉ DE RÉALISATION DE L'ÉVÈNEMENT")
    print(j)
    print(Ui)

    #on remplit la matrice de zéros créée au début avec les valeurs trouvés grâce à la distribution de probabilité calculée ci-dessus

    zi = sigma[j]*np.random.randn(1,1)+m[j]
    z[i]=zi
print(z)

#on affiche les échantillons de z sous forme d'histogramme

import matplotlib.pyplot as mpl

#on génère l'histogramme

histogramme = mpl.hist(z, bins = 50)
print("*HISTOGRAMME*")
mpl.title("Échantillons de z", fontsize=15)
mpl.show()

#on génére le générateur

print("CRÉATION DE MON_GÉNÉRATEUR_PY")

import numpy as np
gen = "mon_générateur_py"
l = np.array([[0.6 , 0.4]])
m = np.cumsum(l)
n = np.array([[-2.3] , [3.3]])
o = np.array([[2] , [3.1]])
N = 5000
q = np.zeros((N , 1))
def gen(l,m,n,o,q):
    for x in range (N):
        Ux = np.random.rand(1,1)
        k = 0
        while(Ux > b[k]):
            k = k+1
        ex = d[k]*np.random.randn(1,1)+c[k]
        e[x]=ex
    return p
q = gen(l,m,n,o,q)
print("RÉSULTAT DE MON GÉNÉRATEUR PY",q)

#on génère l'histogramme empirique dans le support [-7,10] divisé en Nbins = 50 intervalles

import numpy as plt
import matplotlib.pyplot as mpl
mpl.hist(e, range = (-7,10), bins = 50)
print("*HISTOGRAMME EMPIRIQUE*")
mpl.title("HISTOGRAMME EMPIRIQUE", fontsize=15)
mpl.show()