# -*- coding: utf-8 -*-
"""L3_TD3_EF_SIMATOVIC_LUCAS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y70hHs-0qTvZlTCX4E8vlBFCNTS8L6qh
"""

!apt-get install mysql-server > /dev/null
!service mysql start
!mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '!*L3_ECO*!'"
!pip install mysql-connector-python

#ON IMPORT TOUS LES "IMPORT" DONT ON AURA BESOIN

import numpy as np
import mysql.connector as ms

#1) ON SUPPRIME LA BASE DE DONNEES "caviste" SI ELLE EXISTE POUR EVITER LES ERREURS EN CAS DE MODIFICATION

mydb = ms.connect(
    host = 'localhost',
    user = 'root',
    passwd = '!*L3_ECO*!'
)

mycursor = mydb.cursor()
mycursor.execute("DROP DATABASE IF EXISTS caviste")
print(mycursor)

#NOUS CREEONS LA BASE DE DONNEES "caviste" SI ELLE N'EXISTE PAS

mydb = ms.connect(
    host = 'localhost',
    user = 'root',
    passwd = '!*L3_ECO*!'
)

mycursor = mydb.cursor()
mycursor.execute("CREATE DATABASE IF NOT EXISTS caviste")
print(mycursor)

#ENFIN ON SE CONNECTE A LA BASE DE DONNEES "caviste" ET ON DEVELOPPE AVEC LES TABLES DEMANDEES

mydb = ms.connect(
    host = 'localhost',
    user = 'root',
    passwd = '!*L3_ECO*!',
    database = 'caviste'
)

#CREATION DES TABLES

mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS vigneron,vin,commande,buveur,acheter")
print(mycursor)

mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE IF NOT EXISTS vigneron (num_vig INT AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(40), prenom VARCHAR(40), ville VARCHAR(40))")
print(mycursor)

mycursor=mydb.cursor()
mycursor.execute("CREATE TABLE IF NOT EXISTS vin (num_vin INT AUTO_INCREMENT PRIMARY KEY, cru VARCHAR(40), millesime VARCHAR(40), num_vig INT, FOREIGN KEY (num_vig) REFERENCES vigneron(num_vig))")
print(mycursor)

mycursor=mydb.cursor()
mycursor.execute("CREATE TABLE IF NOT EXISTS buveur (num_buv INT AUTO_INCREMENT PRIMARY KEY,  nom VARCHAR(40), prenom VARCHAR(40), ville VARCHAR(40))")
print(mycursor)

mycursor=mydb.cursor()
mycursor.execute("CREATE TABLE IF NOT EXISTS commande (num_com INT AUTO_INCREMENT PRIMARY KEY, date DATE, num_buv INT, FOREIGN KEY (num_buv) REFERENCES buveur(num_buv) )")
print(mycursor)

mycursor=mydb.cursor()
mycursor.execute("CREATE TABLE IF NOT EXISTS acheter (num_vin INT, FOREIGN KEY (num_vin) REFERENCES vin (num_vin),num_com INT, FOREIGN KEY (num_com) REFERENCES commande (num_com), date DATE, quantit DECIMAL(40,0))")
print(mycursor)

#2)NOUS CREEONS UN SCRIPT INSERANT LES RENSIGNEMENTS DE NOTRE CHOIX ; PREMIEREMENT LES NOMS, PRENOMS ET VILLES DES VIGNERONS

mycursor = mydb.cursor()
sql = "INSERT INTO vigneron (nom, prenom, ville) VALUES (%s, %s, %s)"
val = [("CISSE","DJIBRIL","ARLES"),
       ("MUSK","ELON","PRETORIA"),
       ("MENDES","EVA","MIAMI"),
       ("TARDIEUX","ERIC","CARQUEIRANNE")]
mycursor.executemany(sql,val)
mydb.commit()

#DEUXIEMEMENT LE VIN ET SON ANNEE

mycursor = mydb.cursor()
sql = "INSERT INTO vin (cru, millesime) VALUES (%s, %s)"
val = [("Moët & Chandon","2002"),
       ("Le Bordeaux","2005"),
       ("Dom Perignon","2002"),
       ("Dom Perignon","2005")]
mycursor.executemany(sql,val)
mydb.commit()

#TROISIEMEMENT LES DATES ET LEURS QUANTITES COMMANDEES

mycursor = mydb.cursor()
sql = "INSERT INTO acheter (date, quantit) VALUES (%s, %s)"
val = [("2010-11-20","54"),
       ("2021-11-18","46"),
       ("2017-03-05","25"),
       ("2022-06-04","75")]
mycursor.executemany(sql,val)
mydb.commit()

#ET DERNIEREMENT LES NOMS, PRENOMS ET VILLES DES CONSOMMATEURS

mycursor = mydb.cursor()
sql = "INSERT INTO buveur (nom, prenom, ville) VALUES (%s, %s, %s)"
val = [("CRISTIANO","RONALDO","AL-NASSER"),
       ("Drucker","MICHEL","PARIS"),
       ("GREALISH","JACK","MANCHESTER"),
       ("LENNON","JOHN","LIVERPOOL")]
mycursor.executemany(sql,val)
mydb.commit()

#3) NOUS CREONS LE SCRIPT requetes.py ACCOMPOMPAGNE DES INFORMATIONS SUIVANTES
#a) Quels millésime ont été achetés le 18/11/2021?

mycursor = mydb.cursor()
mycursor.execute("SELECT cru,millesime FROM vin "
                 "WHERE date = ALL(select date FROM acheter WHERE "
                 "la date d'achat du millsime = '2021-11-18')")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

#b) Quels sont les vins produits par Eric Tardieux

mycursor = mydb.cursor()
mycursor.execute("SELECT cru, millesime FROM vin "
                 "WHERE ERIC TARDIEUX = ALL(select TARDIEUX,ERIC FROM vigneron WHERE "
                 "il a produit = 'ERIC TARDIEU')")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

#c)  Quel est le nom du client qui a acheté du vin le 18/11/2021

mycursor = mydb.cursor()
mycursor.execute("SELECT nom, prenom, ville FROM buveur "
                 "WHERE date = (select date FROM acheter WHERE "
                 "date d'achat = '2021-11-18')")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)